name: Run Python Script
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If requirements.txt exists
      - name: Run script
        run: python main.py
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tac-output
          path: output.txt
          if-no-files-found: warn
